# Generated by Django 4.1.9 on 2023-05-31 22:53

import api.models.people
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('p_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='P_ID')),
                ('name', models.CharField(max_length=200)),
                ('face', models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to=api.models.people.facesave)),
            ],
        ),
    ]
