# Generated by Django 4.1.9 on 2023-05-25 22:09

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('face', models.ImageField(storage=djongo.storage.GridFSStorage(base_url='myfiles/', collection='myfiles'), upload_to='face')),
            ],
        ),
    ]
